# Generated by Django 4.0.6 on 2022-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
