# Generated by Django 4.0.6 on 2022-08-05 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0005_alter_child_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('points', models.BigIntegerField(default=0)),
                ('child', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parents.child')),
            ],
        ),
    ]
